#!/usr/bin/env python3
"""Checks the Provision DHCP server can serve more than one pool safely.

`dhcpd.conf` stays the single source of truth: it is rewritten from scratch on
every save and read back on every load.  That makes the reader the most
dangerous component in this feature.  Every installation written before this
change nests its single subnet inside `shared-network OOB { ... }`, so a reader
that only recognises a top-level `subnet` returns no pools, and the next save
writes a config with no subnet at all — silently deleting the pool the whole
fleet depends on.  The first class below pins that shape.

The rest covers what multiple pools introduce.  Pool 1 is directly attached and
must own an address on the listen interface; `dhcpd -t` performs no network
operation and a save made while the service is stopped never exercises
interface binding, so nothing but an application-level check notices when that
stops being true.  Pools 2..N are relayed: they are reachable only because an
external relay on another VLAN's gateway forwards requests here, which LLDPq
neither configures nor verifies.  A reservation that falls outside every pool,
or inside a pool's dynamic range, is not a syntax error either — dhcpd accepts
it and then never serves it.

The save paths are executed for real out of the CGI, against a temporary
filesystem, with a fake `ip` on PATH and the transaction/service helpers stubbed
out.  Packet-level relay behaviour cannot be tested here and stays a lab step.
"""

from __future__ import annotations

import ast
import ipaddress
import json
import os
from pathlib import Path
import re
import shutil
import socket
import stat
import subprocess
import tempfile
import textwrap
import time
import unittest
from unittest import mock
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
PROVISION_API = (ROOT / "html" / "provision-api.sh").read_text(encoding="utf-8")
PROVISION_HTML = (ROOT / "html" / "provision.html").read_text(encoding="utf-8")
INSTALL_SH = (ROOT / "install.sh").read_text(encoding="utf-8")
ENTRYPOINT = (ROOT / "docker" / "docker-entrypoint.sh").read_text(encoding="utf-8")

_BODY = PROVISION_API[
    PROVISION_API.index("python3 << 'PYTHON_SCRIPT'\n"):
    PROVISION_API.rindex("\nPYTHON_SCRIPT\n")
]
_TREE = ast.parse(_BODY)

# The two fixtures the pre-existing DHCP tests validate against.  Both must keep
# parsing, so they are pinned here as well as where they came from.
STAGING_FIXTURE = (
    "# live\n"
    "subnet 192.168.100.0 netmask 255.255.255.0 {\n"
    "  range 192.168.100.210 192.168.100.249;\n"
    "}\n"
    'include "/etc/dhcp/dhcpd.hosts";\n'
)  # test_dhcp_validation_staging.py: DhcpValidationStagingTest.live_conf
CONFIG_VALIDATION_FIXTURE = "subnet 10.0.0.0 netmask 255.255.255.0 {}\n"
# test_dhcp_config_validation.py: test_a_foreign_config_is_still_preserved...

LEGACY_WRAPPED_CONF = """# /etc/dhcp/dhcpd.conf - Generated by LLDPq

ddns-update-style none;
authoritative;
log-facility local7;

option www-server code 72 = ip-address;
option default-url code 114 = text;
option cumulus-provision-url code 239 = text;
option space onie code width 1 length width 1;
option onie.installer_url code 1 = text;

option space vivso code width 4 length width 1;
option op125 code 125 = encapsulate vivso;

class "onie-vendor-classes" {
  match if substring(option vendor-class-identifier, 0, 11) = "onie_vendor";
  option vivso.iana 01:01:01;
}

# OOB Management subnet
shared-network OOB {
  subnet 192.168.100.0 netmask 255.255.255.0 {
    range 192.168.100.210 192.168.100.249;
    option routers 192.168.100.1;
    option domain-name "example.com";
    option domain-name-servers 192.168.100.1;
    option www-server 192.168.100.200;
    option default-url "http://192.168.100.200/";
    option cumulus-provision-url "http://192.168.100.200/cumulus-ztp.sh";
    default-lease-time 172800;
    max-lease-time     345600;
  }
}

include "/etc/dhcp/dhcpd.hosts";
"""

LEGACY_GROUPED_HOSTS = """group {

  option domain-name "example.com";
  option domain-name-servers 192.168.100.1;
  option routers 192.168.100.1;
  option www-server 192.168.100.200;
  option default-url "http://192.168.100.200/";
  option cumulus-provision-url "http://192.168.100.200/cumulus-ztp.sh";

host leaf01 {hardware ethernet aa:bb:cc:dd:ee:01; fixed-address 192.168.100.11; \
option host-name "leaf01"; option fqdn.hostname "leaf01"; \
option cumulus-provision-url "http://192.168.100.200/cumulus-ztp.sh";}
}
"""

POOL_FIELDS = ('name', 'subnet', 'netmask', 'range_start', 'range_end',
               'gateway', 'dns', 'domain', 'provision_url', 'lease_time')


def extract_source(name: str) -> str:
    """Slice one top-level def or assignment out of the CGI's embedded Python."""
    for node in _TREE.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            start = min([node.lineno] +
                        [decorator.lineno for decorator in node.decorator_list])
            return "\n".join(_BODY.splitlines()[start - 1:node.end_lineno]) + "\n"
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == name
            for target in node.targets
        ):
            return "\n".join(
                _BODY.splitlines()[node.lineno - 1:node.end_lineno]
            ) + "\n"
    raise AssertionError(f"{name} not found in provision-api.sh")


def heredoc_bodies(text: str, tag: str) -> list[str]:
    """Every `<<'TAG' ... TAG` payload, in source order."""
    opener = f"<<'{tag}'\n"
    closer = f"\n{tag}\n"
    bodies = []
    cursor = 0
    while True:
        start = text.find(opener, cursor)
        if start == -1:
            return bodies
        start += len(opener)
        end = text.index(closer, start)
        bodies.append(text[start:end])
        cursor = end


def entrypoint_python(marker: str) -> str:
    for body in heredoc_bodies(ENTRYPOINT, "PYTHON"):
        if marker in body:
            return body
    raise AssertionError(f"no embedded PYTHON block contains {marker!r}")


def shell_function(text: str, name: str) -> str:
    """Slice one shell function out, skipping over any heredoc it contains.

    Several of these functions emit a config with `}` lines of its own, so the
    first closing brace at column 0 is not the end of the function.
    """
    lines = text[text.index(f"{name}() {{"):].splitlines(keepends=True)
    collected = []
    terminator = None
    for line in lines:
        collected.append(line)
        if terminator is not None:
            if line.strip() == terminator:
                terminator = None
            continue
        opener = re.search(r"<<-?\s*'?([A-Za-z_][A-Za-z0-9_]*)'?", line)
        if opener:
            terminator = opener.group(1)
            continue
        if len(collected) > 1 and line.rstrip("\n") == "}":
            return "".join(collected)
    raise AssertionError(f"{name}() has no closing brace")


class Emitted(BaseException):
    """A CGI response.  Not an Exception, so no `except Exception` swallows it."""

    def __init__(self, payload):
        super().__init__(payload)
        self.payload = payload


# The pool helpers, in dependency order, plus the two save entry points.
API_NAMES = (
    'MAX_DHCP_POOLS', 'DHCP_POOL_NAME_MAX_LENGTH', 'DHCP_POOL_NAME_MARKER',
    'DHCP_POOL_NAME_MARKER_PATTERN', 'DHCP_POOL_NAME_CHARSET',
    'DEFAULT_DHCP_LEASE_TIME', 'DHCP_CONF_PREAMBLE',
    'ip_range_to_list', 'get_dhcp_hosts_path', 'parse_dhcp_hosts',
    'generate_dhcp_hosts', 'dhcp_hosts_bindings_unlocked',
    'is_valid_provision_hostname', 'normalize_inventory_bindings',
    'inventory_revision',
    '_mask_dhcp_comments', '_iter_dhcp_blocks', '_dhcp_block_keyword',
    '_read_dhcp_pool_name_marker', '_read_dhcp_subnet_block', 'parse_dhcp_pools',
    'read_dhcp_conf_text', 'read_dhcp_pools_from_live_config',
    'dhcp_pools_from_parsed', 'read_live_dhcp_pools',
    'annotate_bindings_with_pool', 'read_isc_dhcp_interface',
    'render_isc_dhcp_defaults', 'interface_ipv4_addresses',
    'sanitize_dhcp_pool_name', 'normalize_dhcp_pool', 'normalize_dhcp_pools',
    'validate_primary_pool_is_directly_attached', '_binding_is_dhcp_managed',
    '_binding_address', '_describe_bindings', 'validate_bindings_against_pools',
    'validate_removed_pools', 'validate_pool_protected_addresses',
    'render_dhcp_conf', '_action_save_dhcp_config_locked',
    '_action_save_bindings_locked',
)


class ApiFixture(unittest.TestCase):
    """Runs the real DHCP code from the CGI against a temporary filesystem."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        self.conf_dir = self.root / "etc" / "dhcp"
        self.conf_dir.mkdir(parents=True)
        self.web_root = self.root / "www"
        self.web_root.mkdir()
        self.lldpq_dir = self.root / "lldpq"
        self.lldpq_dir.mkdir()
        self.conf = self.conf_dir / "dhcpd.conf"
        self.hosts = self.conf_dir / "dhcpd.hosts"
        self.isc_default = self.root / "etc" / "isc-dhcp-server"
        self.inventory = self.web_root / "inventory.json"

        self.bin = self.root / "bin"
        self.bin.mkdir()
        self.addresses = self.root / "ip-addresses"
        self.write_interfaces({"ifa": ["192.168.100.200/24"]})
        self.install_fake_ip()

        environment = mock.patch.dict(os.environ, {
            "PATH": f"{self.bin}{os.pathsep}{os.environ.get('PATH', '')}",
            "DHCP_CONF_FILE": str(self.conf),
        }, clear=False)
        environment.start()
        self.addCleanup(environment.stop)
        for name in ("LLDPQ_DHCP_MODE", "DHCP_INTERFACE", "PROVISION_SERVER_IP"):
            os.environ.pop(name, None)

        self.calls = {
            "validated": [], "transactions": [], "rollbacks": [],
            "restarts": [], "conf_updates": [],
        }
        self.running = False
        self.api = self.load_api()

    # ---------- fixtures ----------
    def write_interfaces(self, mapping):
        lines = []
        for name, addresses in mapping.items():
            for address in addresses:
                lines.append(f"{name} {address}")
        self.addresses.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def write_tool(self, name, script):
        path = self.bin / name
        path.write_text("#!/bin/bash\n" + textwrap.dedent(script), encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IEXEC)
        return path

    def install_fake_ip(self):
        """Stand in for iproute2, driven by the address list this test wrote."""
        self.write_tool("ip", f"""
            fixture='{self.addresses}'
            case "$*" in
                "-o link show")
                    index=1
                    printf '%d: lo: <LOOPBACK,UP> mtu 65536 qdisc noqueue\\n' 0
                    cut -d' ' -f1 "$fixture" | sort -u | while read -r name; do
                        printf '%d: %s: <BROADCAST,MULTICAST,UP> mtu 1500\\n' \\
                            "$index" "$name"
                        index=$((index + 1))
                    done
                    ;;
                "-4 -o addr show dev "*)
                    want="${{@: -1}}"
                    grep -- "^$want " "$fixture" | while read -r name address; do
                        printf '2: %s    inet %s scope global %s\\n' \\
                            "$name" "$address" "$name"
                    done
                    ;;
                "-4 -o addr show")
                    while read -r name address; do
                        printf '2: %s    inet %s scope global %s\\n' \\
                            "$name" "$address" "$name"
                    done < "$fixture"
                    ;;
                *) exit 1 ;;
            esac
        """)

    def load_api(self):
        import fcntl
        import hashlib

        test = self

        def atomic_write_text(path, content, mode=0o664):
            with open(path, 'w') as handle:
                handle.write(content)
            os.chmod(path, mode)

        def begin_provision_transaction(kind, candidates, before, after):
            test.calls["transactions"].append((kind, before, after))
            return {"kind": kind, "phase": "begun"}

        def validate_dhcp_config_candidate(conf_content, hosts_content=None,
                                           live_hosts_path=None,
                                           require_binary=True):
            test.calls["validated"].append((conf_content, hosts_content))

        namespace = {
            "os": os, "re": re, "json": json, "time": time, "fcntl": fcntl,
            "hashlib": hashlib, "ipaddress": ipaddress, "socket": socket,
            "subprocess": subprocess, "shutil": shutil, "urlparse": urlparse,
            "DHCP_CONF_FILE": str(self.conf),
            "DHCP_HOSTS_FILE": str(self.hosts),
            "DHCP_HOSTS_ALT": str(self.conf_dir / "dhcpd.host"),
            "ISC_DHCP_DEFAULT_FILE": str(self.isc_default),
            "INVENTORY_FILE": str(self.inventory),
            "INVENTORY_LOCK_FILE": str(self.web_root / ".inventory.lock"),
            "LLDPQ_DIR": str(self.lldpq_dir),
            "POST_DATA": "",
            "result_json": lambda payload: (_ for _ in ()).throw(Emitted(payload)),
            "error_json": lambda message: (_ for _ in ()).throw(
                Emitted({"success": False, "error": message})
            ),
            "atomic_write_text": atomic_write_text,
            "begin_provision_transaction": begin_provision_transaction,
            "mark_provision_transaction":
                lambda journal, phase: journal.update(phase=phase),
            "sync_provision_transaction_targets": lambda journal: None,
            "_clear_provision_transaction": lambda: None,
            "rollback_provision_transaction":
                lambda journal: self.calls["rollbacks"].append(journal),
            "validate_dhcp_config_candidate": validate_dhcp_config_candidate,
            "validate_dhcp_hosts_candidate":
                lambda content, path: self.calls["validated"].append((None, content)),
            "dhcp_is_running": lambda: self.running,
            "restart_dhcp": lambda: (self.calls["restarts"].append(True),
                                     (True, "restarted"))[1],
            "update_lldpq_conf_values":
                lambda updates: self.calls["conf_updates"].append(updates),
            "sync_bindings_to_devices_yaml": None,
            "render_inventory_devices_yaml": None,
        }
        for name in API_NAMES:
            exec(compile(extract_source(name), "provision-api.sh", "exec"),
                 namespace)
        return namespace

    # ---------- helpers ----------
    def pool(self, **overrides):
        payload = {
            "name": "", "subnet": "", "netmask": "255.255.255.0",
            "range_start": "", "range_end": "", "gateway": "", "dns": "",
            "domain": "example.com", "provision_url": "", "lease_time": "172800",
        }
        payload.update(overrides)
        return payload

    def primary(self, **overrides):
        payload = self.pool(
            name="Pool-1", subnet="192.168.100.0",
            range_start="192.168.100.210", range_end="192.168.100.249",
            gateway="192.168.100.1", dns="192.168.100.1",
            provision_url="http://192.168.100.200/cumulus-ztp.sh",
        )
        payload.update(overrides)
        return payload

    def relayed(self, **overrides):
        payload = self.pool(
            name="Pool-2", subnet="10.20.30.0",
            range_start="10.20.30.100", range_end="10.20.30.200",
            gateway="10.20.30.1", dns="10.20.30.1",
        )
        payload.update(overrides)
        return payload

    def normalize(self, *payloads, runtime_server_ip=None):
        return self.api["normalize_dhcp_pools"](list(payloads), runtime_server_ip)

    def render(self, *payloads, hosts_path=None):
        return self.api["render_dhcp_conf"](
            self.normalize(*payloads), hosts_path or str(self.hosts)
        )

    def write_inventory(self, bindings):
        self.inventory.write_text(
            json.dumps({"bindings": bindings, "timestamp": 0}), encoding="utf-8"
        )

    def save_config(self, pools=None, iface="ifa", **extra):
        payload = {"interface": iface}
        if pools is not None:
            payload["pools"] = list(pools)
        payload.update(extra)
        self.api["POST_DATA"] = json.dumps(payload)
        with self.assertRaises(Emitted) as caught:
            self.api["_action_save_dhcp_config_locked"]()
        return caught.exception.payload

    def save_bindings(self, bindings, **extra):
        payload = {"bindings": bindings, "restart_dhcp": False}
        payload.update(extra)
        self.api["POST_DATA"] = json.dumps(payload)
        with self.assertRaises(Emitted) as caught:
            self.api["_action_save_bindings_locked"]()
        return caught.exception.payload

    def subnet_headers(self, conf):
        return re.findall(r'(?m)^subnet\s+([\d.]+)\s+netmask\s+([\d.]+)\s*\{',
                          conf)


class LegacyConfigReadingTests(ApiFixture):
    """The shape every installation written before multi-pool support has."""

    def test_the_legacy_shared_network_wrapper_is_read_as_one_pool(self):
        pools, error = self.api["parse_dhcp_pools"](LEGACY_WRAPPED_CONF)
        self.assertEqual(error, "")
        self.assertEqual(len(pools), 1, "a wrapped subnet must not disappear")
        self.assertEqual(pools[0]["subnet"], "192.168.100.0")
        self.assertEqual(pools[0]["range_start"], "192.168.100.210")
        self.assertEqual(pools[0]["gateway"], "192.168.100.1")
        self.assertEqual(pools[0]["domain"], "example.com")
        self.assertEqual(pools[0]["provision_url"],
                         "http://192.168.100.200/cumulus-ztp.sh")
        self.assertEqual(pools[0]["lease_time"], "172800")

    def test_a_wrapped_config_never_saves_itself_away(self):
        """The regression this whole class exists for: no pools, no subnet."""
        self.conf.write_text(LEGACY_WRAPPED_CONF, encoding="utf-8")
        pools, error = self.api["read_dhcp_pools_from_live_config"]()
        self.assertEqual(error, "")
        payload = self.save_config([
            {field: pools[0][field] for field in POOL_FIELDS}
        ])
        self.assertTrue(payload.get("success"), payload)
        written = self.conf.read_text(encoding="utf-8")
        self.assertEqual(self.subnet_headers(written),
                         [("192.168.100.0", "255.255.255.0")])
        self.assertNotIn("shared-network", written)

    def test_a_wrapper_holding_two_subnets_is_refused_not_flattened(self):
        conf = (
            "shared-network OOB {\n"
            "  subnet 10.1.0.0 netmask 255.255.255.0 "
            "{ range 10.1.0.10 10.1.0.20; }\n"
            "  subnet 10.2.0.0 netmask 255.255.255.0 "
            "{ range 10.2.0.10 10.2.0.20; }\n"
            "}\n"
        )
        pools, error = self.api["parse_dhcp_pools"](conf)
        self.assertEqual(pools, [])
        self.assertIn("same wire", error)
        self.assertIn("2 subnet", error)

    def test_a_wrapper_with_options_at_its_own_scope_is_refused(self):
        conf = (
            "shared-network OOB {\n"
            '  option domain-name "shared.example";\n'
            "  subnet 10.1.0.0 netmask 255.255.255.0 "
            "{ range 10.1.0.10 10.1.0.20; }\n"
            "}\n"
        )
        pools, error = self.api["parse_dhcp_pools"](conf)
        self.assertEqual(pools, [])
        self.assertIn("shared-network scope", error)

    def test_an_unsafe_wrapper_blocks_the_save_with_that_reason(self):
        self.conf.write_text(
            "shared-network OOB {\n"
            "  subnet 10.1.0.0 netmask 255.255.255.0 "
            "{ range 10.1.0.10 10.1.0.20; }\n"
            "  subnet 10.2.0.0 netmask 255.255.255.0 "
            "{ range 10.2.0.10 10.2.0.20; }\n"
            "}\n", encoding="utf-8"
        )
        before = self.conf.read_text(encoding="utf-8")
        payload = self.save_config([self.primary()])
        self.assertFalse(payload["success"])
        self.assertIn("shared-network", payload["error"])
        self.assertEqual(self.conf.read_text(encoding="utf-8"), before)

    def test_the_class_and_option_space_declarations_are_not_pools(self):
        pools, error = self.api["parse_dhcp_pools"](LEGACY_WRAPPED_CONF)
        self.assertEqual(error, "")
        self.assertEqual([pool["subnet"] for pool in pools], ["192.168.100.0"])

    def test_a_commented_out_subnet_is_not_a_pool(self):
        conf = (
            "# subnet 10.9.9.0 netmask 255.255.255.0 {\n"
            "#   range 10.9.9.10 10.9.9.20;\n"
            "# }\n"
            "subnet 192.168.100.0 netmask 255.255.255.0 {\n"
            "  range 192.168.100.210 192.168.100.249;\n"
            "}\n"
        )
        pools, error = self.api["parse_dhcp_pools"](conf)
        self.assertEqual(error, "")
        self.assertEqual([pool["subnet"] for pool in pools], ["192.168.100.0"])

    def test_an_ipv6_subnet_is_refused_rather_than_dropped(self):
        pools, error = self.api["parse_dhcp_pools"](
            "subnet6 2001:db8::/64 {\n  range6 2001:db8::100 2001:db8::200;\n}\n"
        )
        self.assertEqual(pools, [])
        self.assertIn("subnet6", error)

    def test_the_pre_existing_dhcp_test_fixtures_still_parse(self):
        for fixture in (STAGING_FIXTURE, CONFIG_VALIDATION_FIXTURE):
            pools, error = self.api["parse_dhcp_pools"](fixture)
            self.assertEqual(error, "", fixture)
            self.assertEqual(len(pools), 1, fixture)

    def test_an_empty_or_missing_config_yields_no_pools_and_no_error(self):
        self.assertEqual(self.api["parse_dhcp_pools"](""), ([], ""))
        self.assertEqual(self.api["read_dhcp_pools_from_live_config"](), ([], ""))

    def test_a_truncated_config_is_reported_instead_of_read_short(self):
        pools, error = self.api["parse_dhcp_pools"](
            "subnet 192.168.100.0 netmask 255.255.255.0 {\n"
            "  range 192.168.100.210 192.168.100.249;\n"
        )
        self.assertEqual(pools, [])
        self.assertIn("unbalanced braces", error)

    def test_a_brace_inside_a_quoted_value_does_not_confuse_the_reader(self):
        conf = (
            "subnet 192.168.100.0 netmask 255.255.255.0 {\n"
            '  option domain-name "example.com";\n'
            '  option cumulus-provision-url '
            '"http://192.168.100.200/ztp.sh?a={b};c";\n'
            "}\n"
        )
        pools, error = self.api["parse_dhcp_pools"](conf)
        self.assertEqual(error, "")
        self.assertEqual(len(pools), 1)
        self.assertEqual(pools[0]["provision_url"],
                         "http://192.168.100.200/ztp.sh?a={b};c")


class PoolNameTests(ApiFixture):
    def test_a_name_round_trips_through_the_marker_comment(self):
        conf = self.render(self.primary(name="OOB Management"),
                           self.relayed(name="VLAN 11 relayed"))
        self.assertIn('#LLDPQ pool name="OOB Management"', conf)
        pools, error = self.api["parse_dhcp_pools"](conf)
        self.assertEqual(error, "")
        self.assertEqual([pool["name"] for pool in pools],
                         ["OOB Management", "VLAN 11 relayed"])

    def test_a_block_without_a_marker_is_named_by_position(self):
        conf = (
            "subnet 192.168.100.0 netmask 255.255.255.0 { }\n"
            "subnet 10.20.30.0 netmask 255.255.255.0 { }\n"
        )
        pools, _ = self.api["parse_dhcp_pools"](conf)
        self.assertEqual([pool["name"] for pool in pools], ["Pool-1", "Pool-2"])

    def test_an_unrelated_comment_above_a_block_is_not_a_name(self):
        conf = (
            "# OOB Management subnet\n"
            "subnet 192.168.100.0 netmask 255.255.255.0 { }\n"
        )
        pools, _ = self.api["parse_dhcp_pools"](conf)
        self.assertEqual(pools[0]["name"], "Pool-1")

    def test_a_name_cannot_smuggle_a_directive_into_the_config(self):
        """The name lands in a comment line, so a newline would end it."""
        for hostile in ('Pool\nsubnet 10.0.0.0 netmask 255.255.255.0 {}',
                        'Pool"\n', 'Pool\r\noption routers 10.0.0.1;',
                        'Pool\x00', 'Pool#comment', 'Pool;', 'Pool{}',
                        'Pool' * 30):
            with self.subTest(name=hostile):
                with self.assertRaises(ValueError):
                    self.api["sanitize_dhcp_pool_name"](hostile, "Pool-1")
                with self.assertRaises(ValueError):
                    self.normalize(self.primary(name=hostile))

    def test_an_empty_name_falls_back_to_its_position(self):
        pools = self.normalize(self.primary(name=""), self.relayed(name="   "))
        self.assertEqual([pool["name"] for pool in pools], ["Pool-1", "Pool-2"])

    def test_the_accepted_character_set_covers_ordinary_labels(self):
        for name in ("Pool-1", "OOB Management", "vlan_11", "site.a", "Rack 3-B"):
            with self.subTest(name=name):
                self.assertEqual(
                    self.api["sanitize_dhcp_pool_name"](name, "x"), name
                )


class PoolGenerationTests(ApiFixture):
    def test_every_pool_becomes_a_sibling_top_level_subnet(self):
        payloads = [self.primary()] + [
            self.relayed(name=f"Pool-{index}",
                         subnet=f"10.{index}.0.0",
                         range_start=f"10.{index}.0.10",
                         range_end=f"10.{index}.0.20",
                         gateway=f"10.{index}.0.1", dns=f"10.{index}.0.1")
            for index in range(2, 9)
        ]
        conf = self.render(*payloads)
        headers = self.subnet_headers(conf)
        self.assertEqual(len(headers), 8)
        self.assertNotIn("shared-network", conf)
        pools, error = self.api["parse_dhcp_pools"](conf)
        self.assertEqual(error, "")
        self.assertEqual(len(pools), 8)

    def test_more_pools_than_the_cap_are_refused(self):
        payloads = [self.primary()] + [
            self.relayed(name=f"Pool-{index}", subnet=f"10.{index}.0.0",
                         gateway=f"10.{index}.0.1", dns=f"10.{index}.0.1")
            for index in range(2, 10)
        ]
        self.assertEqual(len(payloads), 9)
        with self.assertRaises(ValueError) as caught:
            self.normalize(*payloads)
        self.assertIn("At most 8", str(caught.exception))
        self.assertEqual(self.api["MAX_DHCP_POOLS"], 8)

    def test_at_least_one_pool_is_required(self):
        with self.assertRaises(ValueError):
            self.normalize()

    def test_the_global_option_definitions_are_written_once(self):
        conf = self.render(self.primary(), self.relayed())
        for definition in ("option www-server code 72 = ip-address;",
                           "option default-url code 114 = text;",
                           "option cumulus-provision-url code 239 = text;",
                           'class "onie-vendor-classes" {'):
            self.assertEqual(conf.count(definition), 1, definition)

    def test_a_pool_without_a_provision_url_advertises_no_ztp_options(self):
        conf = self.render(self.primary(), self.relayed(provision_url=""))
        blocks = re.findall(r'(?ms)^subnet[^\n]*\{(.*?)^\}', conf)
        self.assertEqual(len(blocks), 2)
        primary_block, relayed_block = blocks
        for option in ("cumulus-provision-url", "www-server", "default-url"):
            self.assertIn(option, primary_block)
            self.assertNotIn(option, relayed_block)
        self.assertIn("option routers 10.20.30.1;", relayed_block)
        self.assertIn("range 10.20.30.100 10.20.30.200;", relayed_block)
        self.assertIn("default-lease-time 172800;", relayed_block)

    def test_a_primary_pool_can_also_turn_provisioning_off(self):
        conf = self.render(self.primary(provision_url=""))
        block = re.search(r'(?ms)^subnet[^\n]*\{(.*?)^\}', conf).group(1)
        for option in ("cumulus-provision-url", "www-server", "default-url"):
            self.assertNotIn(option, block)
        # The definitions at the top of the file are declarations, not values.
        self.assertIn("option cumulus-provision-url code 239 = text;", conf)

    def test_a_pool_without_a_range_says_so_instead_of_emitting_one(self):
        conf = self.render(self.primary(range_start="", range_end=""))
        self.assertIn("# range not configured", conf)
        self.assertNotIn("range 192.168", conf)

    def test_the_hosts_include_is_written_once(self):
        conf = self.render(self.primary(), self.relayed())
        self.assertEqual(conf.count(f'include "{self.hosts}";'), 1)

    @unittest.skipUnless(shutil.which("dhcpd") or os.path.exists("/usr/sbin/dhcpd"),
                         "dhcpd is not installed on this host")
    def test_a_multi_pool_config_passes_dhcpd_t(self):
        self.hosts.write_text(
            self.api["generate_dhcp_hosts"]([
                {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
                 "ip": "192.168.100.11"},
                {"hostname": "leaf02", "mac": "aa:bb:cc:dd:ee:02",
                 "ip": "10.20.30.11"},
            ])[0], encoding="utf-8"
        )
        self.conf.write_text(
            self.render(self.primary(), self.relayed(provision_url="")),
            encoding="utf-8",
        )
        dhcpd = shutil.which("dhcpd") or "/usr/sbin/dhcpd"
        result = subprocess.run([dhcpd, "-t", "-cf", str(self.conf)],
                                capture_output=True, text=True, timeout=30)
        self.assertEqual(result.returncode, 0,
                         result.stderr or result.stdout)


class PoolValidationTests(ApiFixture):
    def test_overlapping_pools_are_refused(self):
        with self.assertRaises(ValueError) as caught:
            self.normalize(self.primary(),
                           self.relayed(subnet="192.168.100.0",
                                        range_start="", range_end="",
                                        gateway="192.168.100.2",
                                        dns="192.168.100.2"))
        self.assertIn("overlaps", str(caught.exception))

    def test_a_supernet_of_another_pool_is_also_an_overlap(self):
        with self.assertRaises(ValueError):
            self.normalize(
                self.primary(),
                self.relayed(subnet="192.168.0.0", netmask="255.255.0.0",
                             range_start="", range_end="",
                             gateway="192.168.0.1", dns="192.168.0.1"),
            )

    def test_the_subnet_must_be_a_network_address(self):
        with self.assertRaises(ValueError) as caught:
            self.normalize(self.primary(subnet="192.168.100.5"))
        self.assertIn("network address", str(caught.exception))

    def test_a_pool_error_names_the_pool_it_came_from(self):
        with self.assertRaises(ValueError) as caught:
            self.normalize(self.primary(),
                           self.relayed(name="VLAN 11", gateway="10.20.31.1"))
        message = str(caught.exception)
        self.assertIn("Pool 2", message)
        self.assertIn("VLAN 11", message)

    def test_an_empty_provision_url_is_valid_for_every_pool(self):
        pools = self.normalize(self.primary(provision_url=""),
                               self.relayed(provision_url=""))
        for pool in pools:
            self.assertEqual(pool["provision_url"], "")
            self.assertIsNone(pool["server_ip"])
            self.assertEqual(pool["server_base_url"], "")

    def test_a_relative_provision_url_is_still_refused(self):
        with self.assertRaises(ValueError):
            self.normalize(self.primary(provision_url="/cumulus-ztp.sh"))

    def test_the_primary_pool_must_hold_a_listen_interface_address(self):
        pools = self.normalize(self.primary(subnet="10.90.0.0",
                                            range_start="10.90.0.10",
                                            range_end="10.90.0.20",
                                            gateway="10.90.0.1", dns="10.90.0.1",
                                            provision_url=""))
        with self.assertRaises(ValueError) as caught:
            self.api["validate_primary_pool_is_directly_attached"](pools, "ifa")
        message = str(caught.exception)
        self.assertIn("Pool 1", message)
        self.assertIn("ifa", message)
        self.assertIn("192.168.100.200", message)

    def test_the_primary_pool_accepts_any_address_of_that_interface(self):
        self.write_interfaces({"ifa": ["10.90.0.7/24", "192.168.100.200/24"]})
        pools = self.normalize(self.primary())
        self.api["validate_primary_pool_is_directly_attached"](pools, "ifa")

    def test_an_interface_without_an_address_cannot_carry_the_primary_pool(self):
        self.write_interfaces({"ifa": []})
        pools = self.normalize(self.primary())
        with self.assertRaises(ValueError) as caught:
            self.api["validate_primary_pool_is_directly_attached"](pools, "ifa")
        self.assertIn("no IPv4 address", str(caught.exception))

    def test_a_host_that_cannot_be_enumerated_is_not_told_it_is_broken(self):
        self.write_tool("ip", "exit 1\n")
        pools = self.normalize(self.primary(subnet="10.90.0.0",
                                            range_start="", range_end="",
                                            gateway="10.90.0.1", dns="10.90.0.1",
                                            provision_url=""))
        self.api["validate_primary_pool_is_directly_attached"](pools, "ifa")

    def test_a_relayed_pool_needs_no_server_address_of_its_own(self):
        pools = self.normalize(self.primary(), self.relayed())
        self.api["validate_primary_pool_is_directly_attached"](pools, "ifa")
        addresses, _ = self.api["interface_ipv4_addresses"]("ifa")
        self.assertFalse(any(address in pools[1]["network"]
                             for address in addresses))

    def test_a_relayed_gateway_is_not_forced_to_equal_the_relay_source(self):
        """option routers and giaddr are usually one SVI but need not be."""
        pools = self.normalize(self.primary(),
                               self.relayed(gateway="10.20.30.254",
                                            dns="10.20.30.253"))
        self.assertEqual(str(pools[1]["gateway"]), "10.20.30.254")

    def test_protected_addresses_are_judged_per_pool(self):
        pools = self.normalize(self.primary(), self.relayed())
        hosts, _ = self.api["generate_dhcp_hosts"]([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.150"},
        ])
        # 192.168.100.150 sits inside pool 2's numeric range but in pool 1's
        # network, so it must not block pool 2.
        self.assertLess(int(ipaddress.IPv4Address("10.20.30.100")),
                        int(ipaddress.IPv4Address("192.168.100.150")))
        self.api["validate_pool_protected_addresses"](pools, hosts)

    def test_a_range_covering_its_own_reservation_is_refused(self):
        pools = self.normalize(self.primary(), self.relayed())
        hosts, _ = self.api["generate_dhcp_hosts"]([
            {"hostname": "leaf05", "mac": "aa:bb:cc:dd:ee:05",
             "ip": "10.20.30.150"},
        ])
        with self.assertRaises(ValueError) as caught:
            self.api["validate_pool_protected_addresses"](pools, hosts)
        message = str(caught.exception)
        self.assertIn("Pool 2", message)
        self.assertIn("10.20.30.150", message)

    def test_a_range_covering_its_own_gateway_or_server_is_refused(self):
        for overrides in ({"range_start": "192.168.100.1",
                           "range_end": "192.168.100.50"},
                          {"range_start": "192.168.100.200",
                           "range_end": "192.168.100.249"}):
            with self.subTest(**overrides):
                pools = self.normalize(self.primary(**overrides))
                with self.assertRaises(ValueError):
                    self.api["validate_pool_protected_addresses"](pools, "")

    def test_a_provision_server_outside_the_pool_does_not_block_its_range(self):
        pools = self.normalize(
            self.primary(provision_url="http://10.90.0.5/cumulus-ztp.sh")
        )
        self.api["validate_pool_protected_addresses"](pools, "")


class BindingInvariantTests(ApiFixture):
    def setUp(self):
        super().setUp()
        self.pools = self.normalize(self.primary(), self.relayed())

    def check(self, bindings):
        return self.api["validate_bindings_against_pools"](bindings, self.pools)

    def test_a_reservation_outside_every_pool_is_named(self):
        errors = self.check([
            {"hostname": "leaf01", "ip": "192.168.100.11", "dhcp": True},
            {"hostname": "stray", "ip": "172.16.0.9", "dhcp": True},
        ])
        self.assertEqual(len(errors), 1)
        self.assertIn("outside every configured pool", errors[0])
        self.assertIn("stray (172.16.0.9)", errors[0])
        self.assertNotIn("leaf01", errors[0])

    def test_a_reservation_inside_a_dynamic_range_is_named(self):
        errors = self.check([
            {"hostname": "clash", "ip": "10.20.30.150", "dhcp": True},
        ])
        self.assertEqual(len(errors), 1)
        self.assertIn("clash (10.20.30.150)", errors[0])
        self.assertIn("dynamic range", errors[0])
        self.assertIn("Pool-2", errors[0])

    def test_network_broadcast_and_gateway_addresses_are_refused(self):
        for address, reason in (("192.168.100.0", "network address"),
                                ("192.168.100.255", "broadcast address"),
                                ("192.168.100.1", "gateway")):
            with self.subTest(address=address):
                errors = self.check([
                    {"hostname": "leafx", "ip": address, "dhcp": True},
                ])
                self.assertEqual(len(errors), 1)
                self.assertIn(reason, errors[0])

    def test_a_record_with_dhcp_turned_off_is_exempt(self):
        self.assertEqual(self.check([
            {"hostname": "monitored", "ip": "172.16.0.9", "dhcp": False},
            {"hostname": "static-in-range", "ip": "10.20.30.150", "dhcp": False},
        ]), [])

    def test_a_planned_record_without_an_address_is_ignored(self):
        self.assertEqual(self.check([
            {"hostname": "planned", "ip": "", "mac": "-", "dhcp": True},
        ]), [])

    def test_no_pools_yields_no_verdict(self):
        self.assertEqual(
            self.api["validate_bindings_against_pools"](
                [{"hostname": "leaf01", "ip": "192.168.100.11", "dhcp": True}], []
            ), []
        )

    def live(self):
        return self.api["dhcp_pools_from_parsed"]([
            {"name": "VLAN 11", "subnet": "10.20.30.0",
             "netmask": "255.255.255.0"},
        ])

    def test_a_removed_pool_that_still_serves_reservations_is_named(self):
        errors = self.api["validate_removed_pools"](
            self.live(), self.normalize(self.primary()),
            [{"hostname": "leaf05", "ip": "10.20.30.5", "dhcp": True}],
        )
        self.assertEqual(len(errors), 1)
        self.assertIn("VLAN 11", errors[0])
        self.assertIn("leaf05 (10.20.30.5)", errors[0])

    def test_a_removed_pool_without_reservations_is_allowed(self):
        self.assertEqual(self.api["validate_removed_pools"](
            self.live(), self.normalize(self.primary()),
            [{"hostname": "leaf01", "ip": "192.168.100.11", "dhcp": True},
             {"hostname": "static", "ip": "10.20.30.9", "dhcp": False}],
        ), [])

    def test_a_pool_read_without_a_gateway_still_judges_its_reservations(self):
        """A hand-edited file may omit fields the generator always writes."""
        live = self.api["dhcp_pools_from_parsed"]([
            {"name": "Pool-1", "subnet": "192.168.100.0",
             "netmask": "255.255.255.0"},
        ])
        self.assertIsNone(live[0]["gateway"])
        self.assertEqual(self.api["validate_bindings_against_pools"](
            [{"hostname": "leaf01", "ip": "192.168.100.11", "dhcp": True}], live
        ), [])
        errors = self.api["validate_bindings_against_pools"](
            [{"hostname": "stray", "ip": "172.16.0.9", "dhcp": True}], live
        )
        self.assertEqual(len(errors), 1)

    def test_an_unreadable_subnet_is_left_out_rather_than_guessed(self):
        self.assertEqual(self.api["dhcp_pools_from_parsed"]([
            {"name": "broken", "subnet": "not-an-address",
             "netmask": "255.255.255.0"},
        ]), [])


class FlatReservationFileTests(ApiFixture):
    def generate(self, bindings):
        return self.api["generate_dhcp_hosts"](bindings)[0]

    def test_the_reservation_file_has_no_group_block(self):
        content = self.generate([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11"},
        ])
        self.assertNotIn("group", content)
        self.assertIn("host leaf01 {hardware ethernet aa:bb:cc:dd:ee:01;",
                      content)

    def test_a_reservation_carries_no_provisioning_option(self):
        content = self.generate([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11"},
        ])
        for option in ("cumulus-provision-url", "www-server", "default-url",
                       "routers", "domain-name"):
            self.assertNotIn(option, content)

    def test_a_reservation_keeps_only_its_own_identity_options(self):
        content = self.generate([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11"},
        ])
        self.assertIn('option host-name "leaf01";', content)
        self.assertIn('option fqdn.hostname "leaf01";', content)

    def test_incomplete_and_dhcp_disabled_records_are_skipped(self):
        content, skipped = self.api["generate_dhcp_hosts"]([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11"},
            {"hostname": "planned", "mac": "xx:xx:xx:xx:xx:xx",
             "ip": "192.168.100.12"},
            {"hostname": "nomac", "mac": "-", "ip": "192.168.100.13"},
            {"hostname": "static", "mac": "aa:bb:cc:dd:ee:09",
             "ip": "172.16.0.9", "dhcp": False},
            {"hostname": "noip", "mac": "aa:bb:cc:dd:ee:10", "ip": ""},
        ])
        self.assertEqual(skipped, 4)
        self.assertEqual(content.count("host "), 1)
        self.assertIn("leaf01", content)

    def test_the_generated_file_round_trips_through_the_reader(self):
        bindings = [
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11"},
            {"hostname": "leaf02", "mac": "aa:bb:cc:dd:ee:02",
             "ip": "10.20.30.11"},
        ]
        self.hosts.write_text(self.generate(bindings), encoding="utf-8")
        parsed = self.api["parse_dhcp_hosts"](str(self.hosts))
        self.assertEqual([entry["hostname"] for entry in parsed],
                         ["leaf01", "leaf02"])
        self.assertFalse(any(entry["commented"] for entry in parsed))

    def test_the_option_rewriting_helper_is_gone(self):
        """It flattened every option in the file to a single value."""
        self.assertNotIn("rewrite_dhcp_hosts_server_options", PROVISION_API)

    def test_the_reservation_generator_no_longer_reads_the_previous_file(self):
        source = extract_source("generate_dhcp_hosts")
        self.assertNotIn("orig_filepath", source)
        self.assertNotIn("first_host", source)

    def test_reservations_are_labelled_with_the_pool_that_serves_them(self):
        self.conf.write_text(self.render(self.primary(),
                                         self.relayed(name="VLAN 11")),
                             encoding="utf-8")
        bindings = [
            {"hostname": "leaf01", "ip": "192.168.100.11"},
            {"hostname": "leaf05", "ip": "10.20.30.11"},
            {"hostname": "stray", "ip": "172.16.0.9"},
        ]
        self.api["annotate_bindings_with_pool"](bindings)
        self.assertEqual([entry["pool"] for entry in bindings],
                         ["Pool-1", "VLAN 11", ""])


class DhcpConfigSaveTests(ApiFixture):
    def test_two_pools_are_written_as_siblings_with_flat_reservations(self):
        self.write_inventory([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11", "dhcp": True},
            {"hostname": "leaf05", "mac": "aa:bb:cc:dd:ee:05",
             "ip": "10.20.30.11", "dhcp": True},
        ])
        payload = self.save_config([self.primary(),
                                    self.relayed(name="VLAN 11")])
        self.assertTrue(payload["success"], payload)
        self.assertEqual(payload["pools"], 2)
        conf = self.conf.read_text(encoding="utf-8")
        self.assertEqual(len(self.subnet_headers(conf)), 2)
        self.assertNotIn("shared-network", conf)
        self.assertIn('#LLDPQ pool name="VLAN 11"', conf)
        hosts = self.hosts.read_text(encoding="utf-8")
        self.assertNotIn("group", hosts)
        self.assertIn("leaf01", hosts)
        self.assertIn("leaf05", hosts)

    def test_a_grouped_reservation_file_migrates_on_the_first_save(self):
        self.hosts.write_text(LEGACY_GROUPED_HOSTS, encoding="utf-8")
        self.write_inventory([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11", "dhcp": True},
        ])
        payload = self.save_config([self.primary()])
        self.assertTrue(payload["success"], payload)
        hosts = self.hosts.read_text(encoding="utf-8")
        self.assertNotIn("group {", hosts)
        self.assertNotIn("cumulus-provision-url", hosts)
        self.assertIn("host leaf01 {", hosts)

    def test_a_reservation_file_without_an_inventory_is_not_emptied(self):
        self.hosts.write_text(LEGACY_GROUPED_HOSTS, encoding="utf-8")
        payload = self.save_config([self.primary()])
        self.assertTrue(payload["success"], payload)
        self.assertIn("host leaf01 {", self.hosts.read_text(encoding="utf-8"))

    def test_an_explicitly_empty_provision_url_is_not_filled_back_in(self):
        payload = self.save_config([self.primary(provision_url="")])
        self.assertTrue(payload["success"], payload)
        conf = self.conf.read_text(encoding="utf-8")
        block = re.search(r'(?ms)^subnet[^\n]*\{(.*?)^\}', conf).group(1)
        for option in ("cumulus-provision-url", "www-server", "default-url"):
            self.assertNotIn(option, block)
        self.assertEqual(payload["server_ip"], "")
        pools, error = self.api["read_dhcp_pools_from_live_config"]()
        self.assertEqual(error, "")
        self.assertEqual(pools[0]["provision_url"], "")

    def test_the_save_writes_the_supported_interface_key(self):
        payload = self.save_config([self.primary()])
        self.assertTrue(payload["success"], payload)
        self.assertEqual(self.isc_default.read_text(encoding="utf-8"),
                         'INTERFACESv4="ifa"\nINTERFACESv6=""\n')
        self.assertEqual(self.api["read_isc_dhcp_interface"](), "ifa")

    def test_a_primary_pool_off_the_listen_interface_is_refused_when_stopped(self):
        self.running = False
        self.conf.write_text(self.render(self.primary()), encoding="utf-8")
        before = self.conf.read_text(encoding="utf-8")
        payload = self.save_config([
            self.primary(subnet="10.90.0.0", range_start="10.90.0.10",
                         range_end="10.90.0.20", gateway="10.90.0.1",
                         dns="10.90.0.1", provision_url=""),
        ])
        self.assertFalse(payload["success"])
        self.assertIn("Pool 1", payload["error"])
        self.assertIn("ifa", payload["error"])
        self.assertEqual(self.conf.read_text(encoding="utf-8"), before)
        self.assertEqual(self.calls["restarts"], [])

    def test_removing_a_pool_that_still_serves_reservations_is_refused(self):
        self.conf.write_text(self.render(self.primary(),
                                         self.relayed(name="VLAN 11")),
                             encoding="utf-8")
        self.write_inventory([
            {"hostname": "leaf05", "mac": "aa:bb:cc:dd:ee:05",
             "ip": "10.20.30.11", "dhcp": True},
        ])
        before = self.conf.read_text(encoding="utf-8")
        payload = self.save_config([self.primary()])
        self.assertFalse(payload["success"])
        self.assertIn("VLAN 11", payload["error"])
        self.assertIn("leaf05 (10.20.30.11)", payload["error"])
        self.assertEqual(self.conf.read_text(encoding="utf-8"), before)

    def test_removing_an_unused_pool_leaves_the_others_intact(self):
        self.conf.write_text(self.render(self.primary(), self.relayed()),
                             encoding="utf-8")
        self.write_inventory([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11", "dhcp": True},
            {"hostname": "monitored", "mac": "aa:bb:cc:dd:ee:09",
             "ip": "10.20.30.9", "dhcp": False},
        ])
        payload = self.save_config([self.primary()])
        self.assertTrue(payload["success"], payload)
        conf = self.conf.read_text(encoding="utf-8")
        self.assertEqual(self.subnet_headers(conf),
                         [("192.168.100.0", "255.255.255.0")])
        hosts = self.hosts.read_text(encoding="utf-8")
        self.assertIn("host leaf01 {", hosts)
        self.assertNotIn("monitored", hosts)
        self.assertNotIn("group", hosts)

    def test_a_reservation_outside_every_pool_blocks_the_save(self):
        self.write_inventory([
            {"hostname": "stray", "mac": "aa:bb:cc:dd:ee:07",
             "ip": "172.16.0.9", "dhcp": True},
        ])
        payload = self.save_config([self.primary()])
        self.assertFalse(payload["success"])
        self.assertIn("stray (172.16.0.9)", payload["error"])
        self.assertFalse(self.conf.exists())

    def test_a_legacy_flat_body_is_refused_while_extra_pools_exist(self):
        self.conf.write_text(self.render(self.primary(), self.relayed()),
                             encoding="utf-8")
        before = self.conf.read_text(encoding="utf-8")
        payload = self.save_config(None, **self.primary())
        self.assertFalse(payload["success"])
        self.assertIn("out of date", payload["error"])
        self.assertEqual(self.conf.read_text(encoding="utf-8"), before)

    def test_a_legacy_flat_body_still_saves_a_single_pool(self):
        self.conf.write_text(self.render(self.primary()), encoding="utf-8")
        payload = self.save_config(None, **self.primary(domain="single.example"))
        self.assertTrue(payload["success"], payload)
        self.assertIn('option domain-name "single.example";',
                      self.conf.read_text(encoding="utf-8"))

    def test_more_pools_than_the_cap_are_refused_by_the_api(self):
        payloads = [self.primary()] + [
            self.relayed(name=f"Pool-{index}", subnet=f"10.{index}.0.0",
                         range_start="", range_end="",
                         gateway=f"10.{index}.0.1", dns=f"10.{index}.0.1")
            for index in range(2, 10)
        ]
        payload = self.save_config(payloads)
        self.assertFalse(payload["success"])
        self.assertIn("At most 8", payload["error"])

    def test_the_candidate_is_validated_before_anything_is_written(self):
        self.save_config([self.primary()])
        self.assertEqual(len(self.calls["validated"]), 1)
        conf, hosts = self.calls["validated"][0]
        self.assertIn("subnet 192.168.100.0", conf)
        self.assertIn("Generated by LLDPq", hosts)

    def test_a_running_service_is_restarted_and_a_stopped_one_is_not(self):
        self.save_config([self.primary()])
        self.assertEqual(self.calls["restarts"], [])
        self.running = True
        self.save_config([self.primary()])
        self.assertEqual(self.calls["restarts"], [True])


class InventorySaveBindingTests(ApiFixture):
    def setUp(self):
        super().setUp()
        self.conf.write_text(self.render(self.primary(), self.relayed()),
                             encoding="utf-8")

    def test_a_binding_outside_every_pool_blocks_the_inventory_save(self):
        payload = self.save_bindings([
            {"hostname": "stray", "mac": "aa:bb:cc:dd:ee:07",
             "ip": "172.16.0.9", "dhcp": True},
        ])
        self.assertFalse(payload["success"])
        self.assertIn("stray (172.16.0.9)", payload["error"])
        self.assertFalse(self.inventory.exists())

    def test_a_binding_inside_a_dynamic_range_blocks_the_inventory_save(self):
        payload = self.save_bindings([
            {"hostname": "clash", "mac": "aa:bb:cc:dd:ee:08",
             "ip": "10.20.30.150", "dhcp": True},
        ])
        self.assertFalse(payload["success"])
        self.assertIn("dynamic range", payload["error"])

    def test_a_monitored_supplement_outside_every_pool_is_accepted(self):
        payload = self.save_bindings([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11", "dhcp": True},
            {"hostname": "monitored", "mac": "aa:bb:cc:dd:ee:09",
             "ip": "172.16.0.9", "dhcp": False},
        ])
        self.assertTrue(payload["success"], payload)
        self.assertEqual(payload["written"], 1)

    def test_an_unsafe_legacy_wrapper_blocks_the_inventory_save_too(self):
        self.conf.write_text(
            "shared-network OOB {\n"
            "  subnet 10.1.0.0 netmask 255.255.255.0 { }\n"
            "  subnet 10.2.0.0 netmask 255.255.255.0 { }\n"
            "}\n", encoding="utf-8"
        )
        payload = self.save_bindings([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11", "dhcp": True},
        ])
        self.assertFalse(payload["success"])
        self.assertIn("shared-network", payload["error"])

    def test_both_save_paths_produce_the_same_reservation_file(self):
        bindings = [
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11", "dhcp": True},
            {"hostname": "leaf05", "mac": "aa:bb:cc:dd:ee:05",
             "ip": "10.20.30.11", "dhcp": True},
        ]
        self.assertTrue(self.save_bindings(bindings)["success"])
        from_inventory_save = self.hosts.read_text(encoding="utf-8")

        self.hosts.write_text(LEGACY_GROUPED_HOSTS, encoding="utf-8")
        self.assertTrue(self.save_config([self.primary(), self.relayed()])
                        ["success"])
        self.assertEqual(self.hosts.read_text(encoding="utf-8"),
                         from_inventory_save)

    def test_an_installation_without_pools_yet_can_still_save_inventory(self):
        self.conf.unlink()
        payload = self.save_bindings([
            {"hostname": "leaf01", "mac": "aa:bb:cc:dd:ee:01",
             "ip": "192.168.100.11", "dhcp": True},
        ])
        self.assertTrue(payload["success"], payload)

    def test_both_paths_share_one_validator(self):
        for name in ("_action_save_bindings_locked",
                     "_action_save_dhcp_config_locked"):
            source = extract_source(name)
            self.assertIn("validate_bindings_against_pools", source, name)
            self.assertIn("read_live_dhcp_pools()", source, name)


class ListenInterfaceKeyTests(ApiFixture):
    def test_the_supported_key_is_what_gets_written(self):
        self.assertEqual(self.api["render_isc_dhcp_defaults"]("ifa"),
                         'INTERFACESv4="ifa"\nINTERFACESv6=""\n')

    def test_a_legacy_key_is_still_readable(self):
        self.isc_default.write_text('INTERFACES="ifb"\n', encoding="utf-8")
        self.assertEqual(self.api["read_isc_dhcp_interface"](), "ifb")

    def test_the_supported_key_wins_over_the_legacy_one(self):
        self.isc_default.write_text(
            'INTERFACES="ifb"\nINTERFACESv4="ifa"\nINTERFACESv6=""\n',
            encoding="utf-8",
        )
        self.assertEqual(self.api["read_isc_dhcp_interface"](), "ifa")

    def test_an_empty_or_missing_file_yields_no_interface(self):
        self.assertEqual(self.api["read_isc_dhcp_interface"](), "")
        self.isc_default.write_text('INTERFACESv4=""\n', encoding="utf-8")
        self.assertEqual(self.api["read_isc_dhcp_interface"](), "")

    def test_the_direct_start_path_reads_the_same_key(self):
        source = extract_source("restart_dhcp")
        self.assertIn("read_isc_dhcp_interface()", source)
        self.assertNotIn('INTERFACES="', source)

    def test_the_reported_configuration_uses_the_same_reader(self):
        source = extract_source("action_get_dhcp_config")
        self.assertIn("read_isc_dhcp_interface()", source)

    def test_the_docker_entrypoint_writes_and_reads_the_same_key(self):
        self.assertIn('INTERFACESv4="{interface}"', ENTRYPOINT)
        self.assertIn('INTERFACESv6=""', ENTRYPOINT)
        reader = shell_function(ENTRYPOINT, "_read_isc_dhcp_interface")
        self.assertIn("for key in INTERFACESv4 INTERFACES; do", reader)
        self.assertIn('DHCP_IFACE=$(_read_isc_dhcp_interface)', ENTRYPOINT)
        self.assertIn('dhcpd -d -cf /etc/dhcp/dhcpd.conf "$DHCP_IFACE"',
                      ENTRYPOINT)
        self.assertNotRegex(ENTRYPOINT, r"grep -q '\^INTERFACES='")


class DockerProvisioningReferenceTests(unittest.TestCase):
    """The entrypoint must not invent provisioning options or refuse zero."""

    @classmethod
    def setUpClass(cls):
        cls.migration = entrypoint_python("def rewrite(")
        cls.guard = entrypoint_python("def url_addresses(")

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)

    def run_migration(self, conf_text, hosts_text, server_ip):
        source = self.root / "dhcpd.conf"
        destination = self.root / "dhcpd.conf.new"
        hosts_source = self.root / "dhcpd.hosts"
        hosts_destination = self.root / "dhcpd.hosts.new"
        source.write_text(conf_text, encoding="utf-8")
        hosts_source.write_text(hosts_text, encoding="utf-8")
        result = subprocess.run(
            ["python3", "-c", self.migration, str(source), str(destination),
             str(hosts_source), str(hosts_destination), server_ip],
            capture_output=True, text=True, timeout=30,
        )
        return result, destination, hosts_destination

    def run_guard(self, conf_text, hosts_text, server_ip):
        conf = self.root / "guard-dhcpd.conf"
        hosts = self.root / "guard-dhcpd.hosts"
        conf.write_text(conf_text, encoding="utf-8")
        hosts.write_text(hosts_text, encoding="utf-8")
        return subprocess.run(
            ["python3", "-c", self.guard, str(conf), str(hosts), server_ip],
            capture_output=True, text=True, timeout=30,
        )

    def pool_block(self, subnet, provisioning_url=None, server_ip=None):
        lines = [f"subnet {subnet}.0 netmask 255.255.255.0 {{",
                 f"  range {subnet}.100 {subnet}.200;",
                 f"  option routers {subnet}.1;"]
        if provisioning_url:
            lines.append(f"  option www-server {server_ip};")
            lines.append(f'  option default-url "http://{server_ip}/";')
            lines.append(f'  option cumulus-provision-url "{provisioning_url}";')
        lines.append("}")
        return "\n".join(lines) + "\n"

    def test_a_config_where_no_pool_provisions_is_accepted(self):
        conf = self.pool_block("192.168.100") + self.pool_block("10.20.30")
        result, destination, _ = self.run_migration(conf, "", "192.168.100.7")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(destination.read_text(encoding="utf-8"), conf)

    def test_the_runtime_guard_also_accepts_a_zero_option_config(self):
        conf = self.pool_block("192.168.100") + self.pool_block("10.20.30")
        result = self.run_guard(conf, "", "192.168.100.7")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_only_the_host_part_of_an_existing_option_is_rewritten(self):
        conf = self.pool_block(
            "192.168.100",
            "https://192.168.100.5:8443/ztp/cumulus-ztp.sh?role=leaf#top",
            "192.168.100.5",
        )
        result, destination, _ = self.run_migration(conf, "", "192.168.100.7")
        self.assertEqual(result.returncode, 0, result.stderr)
        migrated = destination.read_text(encoding="utf-8")
        self.assertIn(
            'option cumulus-provision-url '
            '"https://192.168.100.7:8443/ztp/cumulus-ztp.sh?role=leaf#top";',
            migrated,
        )
        self.assertIn("option www-server 192.168.100.7;", migrated)
        self.assertIn('option default-url "http://192.168.100.7/";', migrated)

    def test_a_pool_with_provisioning_off_gets_no_options_added(self):
        conf = (self.pool_block("192.168.100",
                                "http://192.168.100.5/cumulus-ztp.sh",
                                "192.168.100.5")
                + self.pool_block("10.20.30"))
        result, destination, _ = self.run_migration(conf, "", "192.168.100.7")
        self.assertEqual(result.returncode, 0, result.stderr)
        migrated = destination.read_text(encoding="utf-8")
        relayed = migrated[migrated.index("subnet 10.20.30.0"):]
        for option in ("www-server", "default-url", "cumulus-provision-url"):
            self.assertNotIn(option, relayed)

    def test_per_pool_values_are_not_flattened_into_one(self):
        conf = (self.pool_block("192.168.100",
                                "http://192.168.100.5/primary-ztp.sh",
                                "192.168.100.5")
                + self.pool_block("10.20.30",
                                  "http://192.168.100.5/relayed-ztp.sh",
                                  "192.168.100.5"))
        result, destination, _ = self.run_migration(conf, "", "192.168.100.7")
        self.assertEqual(result.returncode, 0, result.stderr)
        migrated = destination.read_text(encoding="utf-8")
        self.assertIn('"http://192.168.100.7/primary-ztp.sh"', migrated)
        self.assertIn('"http://192.168.100.7/relayed-ztp.sh"', migrated)

    def test_an_option_pointing_at_another_server_still_fails_the_guard(self):
        conf = self.pool_block("192.168.100",
                               "http://192.168.100.5/cumulus-ztp.sh",
                               "192.168.100.5")
        result = self.run_guard(conf, "", "192.168.100.7")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("www-server", result.stderr)

    def test_a_migrated_config_satisfies_the_guard(self):
        conf = self.pool_block("192.168.100",
                               "http://192.168.100.5/cumulus-ztp.sh",
                               "192.168.100.5")
        result, destination, _ = self.run_migration(conf, "", "192.168.100.7")
        self.assertEqual(result.returncode, 0, result.stderr)
        guard = self.run_guard(destination.read_text(encoding="utf-8"), "",
                               "192.168.100.7")
        self.assertEqual(guard.returncode, 0, guard.stderr)


class DefaultTemplateTests(ApiFixture):
    """The installer and the container must render the shape the reader expects."""

    def render_installer_template(self):
        output = self.root / "installer-dhcpd.conf"
        script = (
            "set -e\n"
            "export LLDPQ_INSTALL_LIB_ONLY=true\n"
            "export LLDPQ_TEST_NO_SUDO=true\n"
            f"source '{ROOT / 'install.sh'}'\n"
            f"render_default_dhcp_config '{output}' '192.168.100.200' "
            f"'{self.hosts}'\n"
        )
        result = subprocess.run(["bash", "-c", script], capture_output=True,
                                text=True, cwd=str(ROOT), timeout=60)
        self.assertEqual(result.returncode, 0, result.stderr)
        return output.read_text(encoding="utf-8")

    def render_docker_template(self):
        output = self.root / "docker-dhcpd.conf"
        function = shell_function(ENTRYPOINT, "_render_docker_dhcp_config")
        result = subprocess.run(
            ["bash", "-c", f"{function}\n_render_docker_dhcp_config "
                           f"'{output}' '192.168.100.200'"],
            capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        return output.read_text(encoding="utf-8")

    def test_both_default_templates_render_one_unwrapped_pool(self):
        for label, conf in (("installer", self.render_installer_template()),
                            ("docker", self.render_docker_template())):
            with self.subTest(template=label):
                self.assertNotIn("shared-network", conf)
                pools, error = self.api["parse_dhcp_pools"](conf)
                self.assertEqual(error, "")
                self.assertEqual(len(pools), 1)
                self.assertEqual(pools[0]["name"], "Pool-1")
                self.assertEqual(pools[0]["subnet"], "192.168.100.0")
                self.assertEqual(pools[0]["gateway"], "192.168.100.1")

    def test_the_fresh_template_carries_the_primary_provision_url_once(self):
        for label, conf in (("installer", self.render_installer_template()),
                            ("docker", self.render_docker_template())):
            with self.subTest(template=label):
                pools, _ = self.api["parse_dhcp_pools"](conf)
                self.assertEqual(
                    pools[0]["provision_url"],
                    "http://192.168.100.200/cumulus-ztp.sh",
                )
                self.assertEqual(
                    len(re.findall(
                        r'option cumulus-provision-url\s+"[^"]+"\s*;', conf
                    )), 1
                )

    def test_a_rendered_template_survives_a_save_round_trip(self):
        self.conf.write_text(self.render_installer_template(), encoding="utf-8")
        pools, error = self.api["read_dhcp_pools_from_live_config"]()
        self.assertEqual(error, "")
        payload = self.save_config([
            {field: pools[0][field] for field in POOL_FIELDS}
        ])
        self.assertTrue(payload["success"], payload)
        again, error = self.api["read_dhcp_pools_from_live_config"]()
        self.assertEqual(error, "")
        self.assertEqual(again, pools)


class DiscoveryIsUntouchedTests(unittest.TestCase):
    def test_the_scan_still_derives_its_range_from_the_first_subnet(self):
        source = extract_source("run_subnet_scan")
        self.assertIn("DISCOVERY_RANGE", source)
        self.assertIn(r"re.search(r'subnet\s+([\d.]+)'", source)
        self.assertNotIn("parse_dhcp_pools", source)

    def test_extra_ranges_remain_an_operator_choice(self):
        """Comma-separated ranges already work, so no code had to change."""
        self.assertIn("Supports: '192.168.100.10-192.168.100.249'",
                      extract_source("ip_range_to_list"))


class ProvisionUiContractTests(unittest.TestCase):
    """The UI half of the same contract, checked without a browser."""

    def test_the_pool_card_is_a_template_not_eight_copies(self):
        self.assertIn("function dhcpPoolCardHtml(", PROVISION_HTML)
        self.assertIn('id="dhcpPoolList"', PROVISION_HTML)
        for field in POOL_FIELDS:
            self.assertEqual(
                len(re.findall(r"dhcpPoolCell\([^,]+, '" + field + r"',",
                               PROVISION_HTML)), 1, field
            )
        # Index-scoped fields, so cloning a card cannot duplicate an element id.
        self.assertIn('data-field="${field}"', PROVISION_HTML)

    def test_the_primary_pool_card_has_no_remove_button(self):
        card = PROVISION_HTML[
            PROVISION_HTML.index("function dhcpPoolCardHtml("):
            PROVISION_HTML.index("function renderDHCPPoolCards(")
        ]
        self.assertIn("const isPrimary = index === 0;", card)
        self.assertIn("Primary / directly attached", card)
        remove = card.index("removeDHCPPool(this)")
        self.assertIn("isPrimary ? '' :", card[:remove])

    def test_a_relayed_card_states_the_external_prerequisite(self):
        self.assertIn("Relayed pool / external relay required", PROVISION_HTML)
        self.assertIn("Relay status is not verified", PROVISION_HTML)
        self.assertIn("LLDPq neither configures nor checks that relay",
                      PROVISION_HTML)

    def test_adding_a_pool_goes_through_the_dark_confirm_modal(self):
        add = PROVISION_HTML[
            PROVISION_HTML.index("function addDHCPPool("):
            PROVISION_HTML.index("function removeDHCPPool(")
        ]
        self.assertIn("showConfirmModal(", add)
        self.assertIn("'Add Relayed Pool'", add)
        self.assertIn("different VLAN", add)
        self.assertIn("relay (helper-address)", add)
        self.assertIn("provisioning disabled", add)

    def test_removing_a_pool_warns_about_leases_and_manual_cleanup(self):
        remove = PROVISION_HTML[
            PROVISION_HTML.index("function removeDHCPPool("):
            PROVISION_HTML.index("async function loadDHCPConfig(")
        ]
        self.assertIn("showConfirmModal(", remove)
        self.assertIn("not</strong> revoked", remove)
        self.assertIn("Discovery Range", remove)
        self.assertIn("relay (helper-address) configuration", remove)

    def test_no_browser_dialog_is_used_anywhere_on_the_page(self):
        for banned in (r"\bconfirm\s*\(", r"\balert\s*\(", r"\bprompt\s*\("):
            hits = [
                match for match in re.findall(banned + r"[^)]*", PROVISION_HTML)
                if "showConfirmModal" not in match
            ]
            self.assertEqual(hits, [], banned)

    def test_the_relay_target_comes_from_the_interface_inside_pool_one(self):
        derivation = PROVISION_HTML[
            PROVISION_HTML.index("function dhcpRelayCandidates("):
            PROVISION_HTML.index("function refreshDhcpRelayInfo(")
        ]
        self.assertIn("dhcpPoolCards()[0]", derivation)
        self.assertIn("ipInSubnet(ip, subnet, netmask)", derivation)
        # Several candidates must be resolved by the admin, never silently.
        self.assertIn("list.indexOf(chosen) === -1 ? '' : chosen", derivation)
        self.assertIn('id="dhcpRelayTarget"', PROVISION_HTML)

    def test_the_page_enforces_the_same_pool_cap_as_the_api(self):
        self.assertIn("let _dhcpMaxPools = 8;", PROVISION_HTML)
        self.assertIn("dhcpPoolCards().length >= _dhcpMaxPools", PROVISION_HTML)

    def test_the_page_sends_and_reads_the_pools_array(self):
        self.assertIn("pools: pools,", PROVISION_HTML)
        self.assertIn("Array.isArray(data.pools)", PROVISION_HTML)
        self.assertNotIn("dhcpProvisionURL", PROVISION_HTML)
        self.assertNotIn("dhcpSubnet", PROVISION_HTML)

    def test_an_unmanageable_config_blocks_saving_from_the_page(self):
        self.assertIn("_dhcpConfigError", PROVISION_HTML)
        self.assertIn("save.disabled = !!_dhcpConfigError", PROVISION_HTML)

    def test_the_reservation_table_shows_the_pool(self):
        table = PROVISION_HTML[
            PROVISION_HTML.index('id="dhcp-hosts-table-container"'):
            PROVISION_HTML.index('id="dhcp-log-source"')
        ]
        self.assertIn(">Pool</th>", table)
        self.assertIn('colspan="5"', table)
        self.assertNotIn('colspan="4"', table)
        renderer = PROVISION_HTML[
            PROVISION_HTML.index("async function loadDHCPHosts("):
            PROVISION_HTML.index("// ===================== DHCP CONFIG")
        ]
        self.assertIn("b.pool ? escHtml(b.pool)", renderer)
        self.assertNotIn('colspan="4"', renderer)

    def test_the_ztp_url_field_says_what_leaving_it_empty_means(self):
        self.assertIn("Empty means no provisioning options are sent for this "
                      "pool: ZTP is off.", PROVISION_HTML)
        self.assertIn("function setDhcpZtpBadge(", PROVISION_HTML)


if __name__ == "__main__":
    unittest.main()
