#!/bin/bash

#
# CUMULUS-AUTOPROVISIONING
# Generated by LLDPq Provision
#

function ping_until_reachable(){
    last_code=1
    max_tries=30
    tries=0
    while [ "0" != "$last_code" ] && [ "$tries" -lt "$max_tries" ]; do
        tries=$((tries+1))
        echo "$(date) INFO: ( Attempt $tries of $max_tries ) Pinging $1 Target Until Reachable."
        ping $1 -c2 --no-vrf-switch &> /dev/null
        last_code=$?
        sleep 1
    done
    if [ "$tries" -eq "$max_tries" ] && [ "$last_code" -ne "0" ]; then
        echo "$(date) ERROR: Reached maximum number of attempts to ping the target $1 ."
        exit 1
    fi
}

function set_password(){
    passwd -x 99999 cumulus
    echo 'cumulus:CumulusLinux!' | chpasswd
}

function resolve_hostname(){
    local serial="$1"
    local mapping_url="http://$IMAGE_SERVER_HOSTNAME/serial-mapping.txt"
    local hostname=""
    local mapping=$(curl -sf "$mapping_url" 2>/dev/null)
    if [ -n "$mapping" ]; then
        hostname=$(echo "$mapping" | grep -v '^#' | awk -v s="$serial" 'tolower($1) == tolower(s) {print $2; exit}')
    fi
    echo "$hostname"
}

function init_ztp(){
    echo "Running ZTP..."

    set_password
    echo "cumulus ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/10_cumulus

    KEY=""
    if [ -n "$KEY" ]; then
        mkdir -p /root/.ssh /home/cumulus/.ssh
        echo "$KEY" >> /root/.ssh/authorized_keys
        echo "$KEY" >> /home/cumulus/.ssh/authorized_keys
        chown -R cumulus:cumulus /home/cumulus/.ssh
        echo "SSH key installed"
    fi

    if [ -n "$CONFIG_URL" ]; then
        echo "Applying generated config for $MY_HOSTNAME..."
        curl -sf "$CONFIG_URL" -o /tmp/startup.yaml
        if [ -s /tmp/startup.yaml ]; then
            nv config replace /tmp/startup.yaml
            nv config apply -y
            nv config save
            echo "Config applied and saved for $MY_HOSTNAME"
        fi
    fi

    exit 0
}

IMAGE_SERVER_HOSTNAME=__IMAGE_SERVER_IP__
CUMULUS_TARGET_RELEASE=__TARGET_OS_VERSION__
CUMULUS_CURRENT_RELEASE=$(grep RELEASE /etc/lsb-release | cut -d "=" -f2)
IMAGE_SERVER=http://$IMAGE_SERVER_HOSTNAME/cumulus-linux-$CUMULUS_TARGET_RELEASE-mlx-amd64.bin
ZTP_URL=http://$IMAGE_SERVER_HOSTNAME/cumulus-ztp.sh

MY_SERIAL=$(decode-syseeprom 2>/dev/null | awk '/Serial Number/ {print $NF; exit}')
[ -z "$MY_SERIAL" ] && MY_SERIAL=$(onie-syseeprom -g 0x23 2>/dev/null | tr -d ' ')
echo "Serial: $MY_SERIAL"

MY_HOSTNAME=$(resolve_hostname "$MY_SERIAL")
echo "Resolved hostname: $MY_HOSTNAME"

CONFIG_URL=""
if [ -n "$MY_HOSTNAME" ]; then
    URL="http://$IMAGE_SERVER_HOSTNAME/generated_config_folder/${MY_HOSTNAME}.yaml"
    if curl -sf --head "$URL" 2>/dev/null | head -1 | grep -q "200"; then
        CONFIG_URL="$URL"
        echo "Config available: $CONFIG_URL"
    else
        echo "No generated config found for $MY_HOSTNAME"
    fi
else
    echo "Serial $MY_SERIAL not found in mapping; no config will be applied"
fi

echo "Checking if the device is running the correct version..."
if [ "$CUMULUS_TARGET_RELEASE" != "$CUMULUS_CURRENT_RELEASE" ]; then
    echo "Version mismatch: $CUMULUS_CURRENT_RELEASE -> $CUMULUS_TARGET_RELEASE"
    ping_until_reachable $IMAGE_SERVER_HOSTNAME
    if [ -n "$CONFIG_URL" ]; then
        echo "Installing OS + config for $MY_HOSTNAME..."
        /usr/cumulus/bin/onie-install -fa -i $IMAGE_SERVER -z $ZTP_URL -t $CONFIG_URL && reboot
    else
        echo "Installing OS only (no config)..."
        /usr/cumulus/bin/onie-install -fa -i $IMAGE_SERVER -z $ZTP_URL && reboot
    fi
else
    echo "Version is correct: $CUMULUS_TARGET_RELEASE"
    init_ztp
fi
