#!/bin/bash

#
# CUMULUS-AUTOPROVISIONING
# Generated by LLDPq Provision
# LLDPQ_ZTP_TEMPLATE_VERSION=2
#

function ping_until_reachable(){
    local target="${1-}"
    local max_tries=30
    local tries=0

    if [ -z "$target" ]; then
        echo "$(date) ERROR: Image server target is empty." >&2
        return 1
    fi
    while [ "$tries" -lt "$max_tries" ]; do
        tries=$((tries+1))
        echo "$(date) INFO: ( Attempt $tries of $max_tries ) Pinging $target Target Until Reachable."
        if ping "$target" -c2 --no-vrf-switch >/dev/null; then
            return 0
        fi
        sleep 1
    done
    echo "$(date) ERROR: Reached maximum number of attempts to ping the target $target ." >&2
    return 1
}

function set_password(){
    passwd -x 99999 cumulus &&
        echo 'cumulus:Nvidia@123' | chpasswd
}

function get_current_release(){
    local release_file="${1:-/etc/lsb-release}"
    local release=""

    release=$(LC_ALL=C awk -F= '
        $1 == "DISTRIB_RELEASE" {
            print substr($0, index($0, "=") + 1)
            found = 1
            exit
        }
        $1 == "RELEASE" { fallback = substr($0, index($0, "=") + 1) }
        END { if (!found && fallback != "") print fallback }
    ' "$release_file") || return 1
    release=${release%$'\r'}
    case "$release" in
        \"*\") release=${release#\"}; release=${release%\"} ;;
        \'*\') release=${release#\'}; release=${release%\'} ;;
    esac
    [[ "$release" =~ ^[0-9][A-Za-z0-9._-]{0,63}$ ]] || return 1
    printf '%s\n' "$release"
}

function is_valid_serial(){
    local serial="${1-}"
    [[ -n "$serial" && ${#serial} -le 128 && "$serial" =~ ^[[:alnum:]_.:-]+$ ]]
}

function select_hostname_from_mapping(){
    local serial="${1-}"
    local mapping="${2-}"

    if ! is_valid_serial "$serial" || [ -z "$mapping" ]; then
        return 2
    fi

    printf '%s\n' "$mapping" | LC_ALL=C awk -v wanted="$serial" '
        function serial_ok(value) {
            return length(value) > 0 && length(value) <= 128 && \
                value ~ /^[[:alnum:]_.:-]+$/
        }
        function hostname_ok(value) {
            return length(value) > 0 && length(value) <= 253 && \
                value ~ /^[[:alnum:]][[:alnum:]_.-]*$/
        }
        BEGIN { wanted = tolower(wanted) }
        { sub(/\r$/, "") }
        /^[[:space:]]*(#|$)/ { next }
        {
            if (NF != 2 || !serial_ok($1) || !hostname_ok($2)) {
                invalid = 1
                next
            }
            serial_key = tolower($1)
            hostname_key = tolower($2)
            if (++seen_serial[serial_key] > 1 || ++seen_hostname[hostname_key] > 1) {
                invalid = 1
            }
            if (serial_key == wanted) {
                matches++
                hostname = $2
            }
        }
        END {
            if (invalid || matches > 1) exit 2
            if (matches == 1) {
                print hostname
                exit 0
            }
            exit 1
        }
    '
}

function resolve_hostname(){
    local serial="${1-}"
    local mapping_url="http://$IMAGE_SERVER_HOSTNAME/serial-mapping.txt"
    local mapping=""

    if ! is_valid_serial "$serial"; then
        return 2
    fi
    if ! mapping=$(curl --fail --silent --show-error --connect-timeout 5 \
        --max-time 15 --retry 2 -- "$mapping_url"); then
        echo "Unable to download serial mapping from $mapping_url" >&2
        return 2
    fi
    if [ "${#mapping}" -gt 8388608 ]; then
        echo "Serial mapping is too large" >&2
        return 2
    fi
    select_hostname_from_mapping "$serial" "$mapping"
}

function find_config_url(){
    local hostname="${1-}"
    local destination="${2-}"
    local extension=""
    local url=""
    local candidate=""
    local http_code=""
    local byte_count=0

    [[ -n "$hostname" && ${#hostname} -le 253 && \
        "$hostname" =~ ^[[:alnum:]][[:alnum:]_.-]*$ ]] || return 2
    [ -n "$destination" ] || return 2
    candidate="${destination}.download"
    rm -f -- "$candidate"

    for extension in yaml yml; do
        url="http://$IMAGE_SERVER_HOSTNAME/generated_config_folder/${hostname}.${extension}"
        if ! http_code=$(curl --silent --show-error --connect-timeout 5 \
            --max-time 60 --retry 2 --output "$candidate" \
            --write-out '%{http_code}' -- "$url"); then
            rm -f -- "$candidate"
            echo "Unable to download generated config from $url" >&2
            return 2
        fi
        case "$http_code" in
            200)
                if [ ! -s "$candidate" ]; then
                    rm -f -- "$candidate"
                    echo "Generated config from $url is empty" >&2
                    return 2
                fi
                byte_count=$(wc -c < "$candidate") || {
                    rm -f -- "$candidate"
                    return 2
                }
                if [ "$byte_count" -gt 16777216 ]; then
                    rm -f -- "$candidate"
                    echo "Generated config from $url is too large" >&2
                    return 2
                fi
                mv -f -- "$candidate" "$destination" || return 2
                printf '%s\n' "$url"
                return 0
                ;;
            404)
                rm -f -- "$candidate"
                ;;
            *)
                rm -f -- "$candidate"
                echo "Generated config request failed with HTTP $http_code: $url" >&2
                return 2
                ;;
        esac
    done
    return 1
}

function install_authorized_key(){
    local directory="${1-}"
    local owner="${2-}"
    local group="${3-}"
    local authorized_keys="$directory/authorized_keys"

    [ -n "$KEY" ] || return 0
    mkdir -p "$directory" || return 1
    chmod 700 "$directory" || return 1
    touch "$authorized_keys" || return 1
    if ! grep -Fqx -- "$KEY" "$authorized_keys"; then
        if [ -s "$authorized_keys" ] &&
            [ "$(tail -c 1 "$authorized_keys" | wc -l)" -eq 0 ]; then
            printf '\n' >> "$authorized_keys" || return 1
        fi
        printf '%s\n' "$KEY" >> "$authorized_keys" || return 1
    fi
    chmod 600 "$authorized_keys" || return 1
    chown "$owner:$group" "$directory" "$authorized_keys" || return 1
}

function install_cumulus_sudoers(){
    local target=/etc/sudoers.d/10_cumulus
    local staged=""

    staged=$(mktemp /etc/sudoers.d/.10_cumulus.XXXXXX) || return 1
    if ! printf '%s\n' 'cumulus ALL=(ALL) NOPASSWD:ALL' > "$staged" || \
        ! chmod 440 "$staged"; then
        rm -f "$staged"
        return 1
    fi
    if command -v visudo >/dev/null 2>&1 && ! visudo -cf "$staged" >/dev/null; then
        rm -f "$staged"
        return 1
    fi
    mv -f "$staged" "$target"
}

function apply_generated_config(){
    local staged="${1-}"

    if [ ! -s "$staged" ]; then
        echo "Generated config is missing or empty" >&2
        return 1
    fi
    command -v nv >/dev/null 2>&1 || return 1
    if ! nv config replace "$staged" || ! nv config apply -y || ! nv config save; then
        echo "Failed to apply generated config for ${MY_HOSTNAME-unknown}" >&2
        return 1
    fi
    echo "Config applied and saved for ${MY_HOSTNAME-unknown}"
}

function init_ztp(){
    echo "Running ZTP..."

    if ! set_password; then
        echo "Failed to set the cumulus password" >&2
        return 1
    fi
    if ! install_cumulus_sudoers; then
        echo "Failed to install the cumulus sudoers policy" >&2
        return 1
    fi

    KEY=""
    if [ -n "$KEY" ]; then
        if ! install_authorized_key /root/.ssh root root || \
            ! install_authorized_key /home/cumulus/.ssh cumulus cumulus; then
            echo "Failed to install the SSH key" >&2
            return 1
        fi
        echo "SSH key installed"
    fi

    if [ -n "${CONFIG_FILE-}" ]; then
        echo "Applying generated config for $MY_HOSTNAME..."
        apply_generated_config "$CONFIG_FILE" || return 1
    fi
    return 0
}

function main(){
    umask 077

    IMAGE_SERVER_HOSTNAME=__IMAGE_SERVER_IP__
    CUMULUS_TARGET_RELEASE=__TARGET_OS_VERSION__
    if ! CUMULUS_CURRENT_RELEASE=$(get_current_release); then
        echo "Unable to determine the current Cumulus release; refusing OS install" >&2
        return 1
    fi
    if ! [[ "$CUMULUS_TARGET_RELEASE" =~ ^[0-9][A-Za-z0-9._-]{0,63}$ ]]; then
        echo "Invalid target Cumulus release" >&2
        return 1
    fi
    IMAGE_SERVER=http://$IMAGE_SERVER_HOSTNAME/cumulus-linux-$CUMULUS_TARGET_RELEASE-mlx-amd64.bin
    ZTP_URL=http://$IMAGE_SERVER_HOSTNAME/cumulus-ztp.sh
    IMAGE_SERVER_PING_TARGET=${IMAGE_SERVER_HOSTNAME%%:*}
    WORK_DIR=$(mktemp -d /tmp/lldpq-ztp.XXXXXX) || return 1
    trap 'rm -rf -- "${WORK_DIR-}"' EXIT

    MY_SERIAL=$(decode-syseeprom 2>/dev/null | awk '/Serial Number/ {print $NF; exit}')
    [ -z "$MY_SERIAL" ] && MY_SERIAL=$(onie-syseeprom -g 0x23 2>/dev/null | tr -d '[:space:]')
    echo "Serial: $MY_SERIAL"

    MY_HOSTNAME=$(resolve_hostname "$MY_SERIAL")
    mapping_status=$?
    case "$mapping_status" in
        0) ;;
        1) MY_HOSTNAME="" ;;
        *)
            echo "Serial mapping validation or download failed; refusing provisioning" >&2
            return 1
            ;;
    esac
    echo "Resolved hostname: $MY_HOSTNAME"

    CONFIG_URL=""
    CONFIG_FILE=""
    if [ -n "$MY_HOSTNAME" ]; then
        CONFIG_FILE="$WORK_DIR/startup.yaml"
        CONFIG_URL=$(find_config_url "$MY_HOSTNAME" "$CONFIG_FILE")
        config_status=$?
        case "$config_status" in
            0) echo "Config downloaded and verified: $CONFIG_URL" ;;
            1)
                CONFIG_URL=""
                CONFIG_FILE=""
                echo "No generated config found for $MY_HOSTNAME"
                ;;
            *)
                echo "Generated config lookup failed; refusing provisioning" >&2
                return 1
                ;;
        esac
    else
        echo "Serial $MY_SERIAL was not resolved; no config will be applied"
    fi

    echo "Checking if the device is running the correct version..."
    if [ "$CUMULUS_TARGET_RELEASE" != "$CUMULUS_CURRENT_RELEASE" ]; then
        echo "Version mismatch: $CUMULUS_CURRENT_RELEASE -> $CUMULUS_TARGET_RELEASE"
        ping_until_reachable "$IMAGE_SERVER_PING_TARGET" || return 1
        if [ -n "$CONFIG_FILE" ]; then
            echo "Installing OS + config for $MY_HOSTNAME..."
            /usr/cumulus/bin/onie-install -fa -i "$IMAGE_SERVER" -z "$ZTP_URL" \
                -t "$CONFIG_FILE" || return 1
        else
            echo "Installing OS only (no config)..."
            /usr/cumulus/bin/onie-install -fa -i "$IMAGE_SERVER" -z "$ZTP_URL" || return 1
        fi
        rm -rf -- "$WORK_DIR"
        trap - EXIT
        reboot || return 1
    else
        echo "Version is correct: $CUMULUS_TARGET_RELEASE"
        init_ztp || return 1
        rm -rf -- "$WORK_DIR"
        trap - EXIT
    fi
    return 0
}

# ---- Main ----

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
